#!/usr/bin/env python3

import os
import logging
import argparse
import getpass
import json
from subprocess import DEVNULL

logging.basicConfig(format='%(message)s', level=logging.DEBUG)
logger = logging.getLogger(__name__)

DEVKIT_GAME_FOLDER = os.path.expanduser('~/devkit-game')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--verbose', required=False, action='store_true')
    conf = parser.parse_args()

    if conf.verbose:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    ret = []
    if os.path.isdir(DEVKIT_GAME_FOLDER):
        for filename in os.listdir(DEVKIT_GAME_FOLDER):
            gamefolder = os.path.join(DEVKIT_GAME_FOLDER, filename)
            if os.path.isdir(gamefolder):
                ret.append( {
                    'gameid': filename,
                } )

    print(json.dumps(ret))
